# Specifies the version of the Docker Compose file format
version: '3.8'

services:
  springboot-app: # Backend service configuration
    build: 
      context: ./chatbot
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_AI_OPENAI_API_KEY="<OPENAI_API_KEY>"
    networks:
      - app-network

  react-ui: # Frontend service configuration
    build: 
      context: ./chatbot-ui
      dockerfile: Dockerfile
    ports:
      - "3000:80" 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
